Allow using environment as default for arguments
dontnod/nimp pull request #35
Opened 2022-08-24 09:13 UTC by phisko

+ Add `--user-config` argument for passing an additional `.conf` file

2022-08-26 11:33 UTC, tdesveaux requested changes

2022-08-26 11:33 UTC, tdesveaux commented on nimp/environment.py
> +        self.set_parser_defaults(parser)
I'd rather it be an opt-in for now before we roll this out so that we can do the necessary checks in our current setup.

2022-08-26 11:33 UTC, tdesveaux commented on nimp/command.py
> +        env.set_parser_defaults(command_parser)
Same here, should be an opt-in

2022-08-26 14:41 UTC, phisko commented on nimp/environment.py
> +        self.set_parser_defaults(parser)
Added an option in cdbc72b8b9b3e13c77006c7c0ef5d59064d8ddeb

2022-08-26 14:41 UTC, phisko commented on nimp/command.py
> +        env.set_parser_defaults(command_parser)
Added an option in cdbc72b8b9b3e13c77006c7c0ef5d59064d8ddeb

2022-08-31 09:24 UTC, tdesveaux commented on nimp/environment.py
> +            if not self._load_nimp_conf(parent_args.user_config):
Sorry, should have seen this before.

Since `self._load_nimp_conf` modify [`self.root_dir`](https://github.com/phisko/nimp/blob/cdbc72b8b9b3e13c77006c7c0ef5d59064d8ddeb/nimp/environment.py#L313), isn't this problematic?

2022-08-31 09:32 UTC, phisko commented on nimp/environment.py
> +            if not self._load_nimp_conf(parent_args.user_config):
After some testing it doesn't seem to be issue, as it gets overwritten [in _load_project_conf](https://github.com/dontnod/nimp/blob/dev/nimp/environment.py#L313), called [right after](https://github.com/dontnod/nimp/blob/dev/nimp/environment.py#L153)

2022-08-31 09:36 UTC, tdesveaux approved these changes

2022-08-31 09:43 UTC, merged