command package: basic support for multiple packages (based on variants) for PS5
dontnod/nimp pull request #50
Opened 2022-11-30 16:53 UTC by avudnez

2022-12-05 16:10 UTC, jasugun commented on nimp/base_commands/package.py
> +            shutil.copyfile(package_configuration.src_title_conf, package_configuration.dst_title_conf)
This will fail because `package_configuration.dst_title_conf` is a perforced read-only file on build agents.
Also, this setup is never reverted anywhere in the process.

I feel this code could be added the the `configure_variant `context manager.
- So we can checkout the conf file if needed; Then perform the copy
- Revert the change when exitting the context manager (by reverting through perforce, or copying back a backup, I think that's done with some ini files already)

However, it feels tedious to have to specifiy p4 args each time we have to package a build now...

2022-12-05 16:13 UTC, jasugun commented on nimp/base_platforms/ps5.py
> +            if not os.path.exists(json_file_path):
This check could just be indented back one bit and apply to both json_file_path?

2022-12-05 16:26 UTC, jasugun commented on nimp/base_commands/package.py
> +            # Since UE only supports application packages (with patches), we need to modify the .gp5
There is a whole lot of code here.
We could have something like the following? (we could end up adding more configure stuff for other platforms right?)
if package_configuration.target_platform == 'PS5' and env.dlc:
    self.configure_packaging_for_ps5_dlc(env, package_configuration

Totally not your doing but you can get rid the the commented crap before :)

2022-12-05 16:37 UTC, jasugun requested changes
The `setup_variant_files` will fail on build agents because we're trying to overwrite perforced read-only file.
We could try and checkout the file, feel tedious...
We could mess with the files attributes instead...
Another idea maybe??

In any case, we have to revert the process.
This function is a good candidate for addition in the `configure_variant` context manager rather than calling it twice (in the staging step, and packaging step).

2022-12-05 16:39 UTC, jasugun commented on nimp/base_commands/package.py
> +            logging.info(f"Copying '{package_configuration.src_title_conf}' to '{package_configuration.dst_title_conf}'")
I think the simple quotes are not needed.

2022-12-05 16:52 UTC, avudnez commented on nimp/base_commands/package.py
> +            shutil.copyfile(package_configuration.src_title_conf, package_configuration.dst_title_conf)
The idea was to remove the actual conf file from source control, as every nimp command needing it will make sure to copy the correct one from the variant's folder.

2022-12-05 17:47 UTC, jasugun commented on nimp/base_commands/package.py
> +            shutil.copyfile(package_configuration.src_title_conf, package_configuration.dst_title_conf)
In that case this code is fine, however I still think it should be called in the `configure_variant` context manger (with a cleanup on exit)

2022-12-06 15:52 UTC, jasugun commented on nimp/base_commands/package.py
> +                _try_remove(dst_title_conf, False)
worst case scenario, `dst_title_conf` could be uninitialized when going through the `finally `portion of the code.
`dst_title_conf = env.format('{uproject_dir}/Platforms/PS5/Build/TitleConfiguration.json')` should be defined outside of the try clause.

2022-12-06 15:55 UTC, jasugun requested changes
`dst_title_conf` shoud be moved outside of the `try: `so it's initialized in any case when going through `finally`, in the `configure_variant `context manager.

The rest is fine, thanks for the addition !

2022-12-08 10:42 UTC, jasugun approved these changes
Thanks for the feature.

2022-12-08 10:43 UTC, merged