improve summary log report (errors first + rm info lvl)
dontnod/nimp pull request #53
Opened 2022-12-14 18:01 UTC by ftith

2022-12-15 09:32 UTC, jasugun commented on nimp/summary.py
> +            for line in self.__dict__["_{0}_stack".format(lvl)]:
if feels hack-ish to access `__dict__ `of an object directly.
We could access `_warnings_stack  `and `_errors_stack ` with getattr()?

```
for lvl in ['errors', 'warnings']:
            for line in getattr(self, f'_{lvl}_stack'):
```

2022-12-15 09:36 UTC, jasugun commented on nimp/summary.py
> +            for line in self.__dict__["_{0}_stack".format(lvl)]:
Another options is to have `self._summary` be a dict of errors and warnings lists.

`self._summary['errors'] += ['[  ERROR  ] %s\n' % (msg,)]`
...etc 

then iterate the dict:
```
for lvl in ['errors', 'warnings']:
            for line in self._summary[lvl]:
```

2022-12-15 09:37 UTC, jasugun requested changes
I really feel acessing __dict__ is hacking and there are other options to achieve something similar.

2022-12-15 09:49 UTC, tdesveaux commented on nimp/summary.py
>          self._has_warnings = False
Both `_has_errors` and `_has_warnings` could be replace with a check on the new `_stack` arrays

2022-12-15 09:49 UTC, tdesveaux commented on nimp/summary.py
> +        destination.close()
`_write_summary` is called from a `with open` context, you do not need to close `destination` (and should not do this here. The place that open a file is responsible for closing it, else it leads to hard to follow code)

2022-12-15 09:49 UTC, tdesveaux commented on nimp/summary.py
> +                destination.write(line)
You could use `writeline` here and remove the line endings from the string you push in the stacks.

2022-12-15 09:49 UTC, tdesveaux commented on nimp/summary.py
> +            for line in self.__dict__["_{0}_stack".format(lvl)]:
You could do something cleaner with:
```
for lvl in [self._errors_stack, self._warnings_stack]:
    destination.writelines(lvl)
```

2022-12-15 09:49 UTC, tdesveaux commented on nimp/summary.py
> +                self._errors_stack += ['[  NOTIF  ] %s\n' % (self._context.popleft(),)]
a cleaner way would be:
```
if len(self._context) == self._context.maxlen:
    self._errors_stack += ['[ NOTIF ] %s\n' % (e,) for e in self._context]
    self._content.clear()
```

2022-12-15 09:49 UTC, tdesveaux commented on nimp/summary.py
>      def _add_error(self, msg):
Both `_add_error` and `_add_warning` could be refactored into one function that take 2 args:
- msg pre-formatted with `'[ WARNING ] %s\n' % (msg,)`
- stack (_errors_stack or warnings_stack)

2022-12-15 16:58 UTC, ftith commented on nimp/summary.py
> +                self._errors_stack += ['[  NOTIF  ] %s\n' % (self._context.popleft(),)]
I've got the following error using self._content.clear()

`AttributeError: 'DefaultSummaryHandler' object has no attribute '_content'`

2022-12-16 09:49 UTC, jasugun commented on nimp/summary.py
> +        self._summary['%ss' % notif_lvl] += ['\n *********************************************\n']
Definetely not the norm in nimp I know, but I think we should enforce fstrings whenever we can in our new code.
like `self._summary[f'{notif_lvl}s]`

2022-12-16 09:51 UTC, tdesveaux approved these changes

2022-12-16 09:51 UTC, tdesveaux commented on nimp/summary.py
> +        return len(self._summary['errors']) > 0
Since you init with `{}`, key might not exists

2022-12-16 10:02 UTC, jasugun approved these changes
Good job, simplified code, same level of functionnality ==  better
fstrings for the win :)

2022-12-16 10:35 UTC, tdesveaux commented on nimp/summary.py
> +        return len(self._summary['errors']) > 0
This initialization is done in `DefaultSummaryHandler` which is a subclass.
`has_` are in the parent (`SummaryHandler`) so if someone else inherit from it, this won't work.

2022-12-16 11:11 UTC, merged

2022-12-16 11:17 UTC, jasugun approved these changes

2022-12-16 11:17 UTC, jasugun commented on nimp/summary.py
> +        self._summary[f'{notif_lvl}s'] += ['[ ' + notif_lvl.upper() + ' ] %s\n' % (msg,)]
Doesn't the fstring work on the second part?  `self._summary[f'{notif_lvl}s'].append(f'[  {notif_lvl.upper()}  ] {msg}\n'])`

2022-12-16 11:17 UTC, jasugun commented on nimp/summary.py
> +        self._summary[f'{notif_lvl}s'] += ['[ ' + notif_lvl.upper() + ' ] %s\n' % (msg,)]
Usually, `append() ` and `extend()` function are more efficient that `+=` in python when handling lists.