Lca/xsx encryption
dontnod/nimp pull request #87
Opened 2023-07-17 16:32 UTC by jasugun

First attempt a implementing xsx /lk encryption.
Needs conf to have the following:
`"xsx_encryption_file": "{uproject_dir}/Config/XSX/project.lekb",`

lekb est supposed to be a sensitive file with restricted access rights.
The cekb file ouput by the process is also sensitive stuff.

I've built a key and a package with it using this method, QA tested it and told me it installed and worked just fine (as long as the cekb file is in there with the build).

I'm unsure specifying a path in the project conf is the way to go but am sharing this as a start so we can think about this and carry on with modifications if needed.

2023-07-18 17:41 UTC, ftith commented on nimp/base_commands/package.py
> +            #     package_command += [ '-NoCompile' ]
Question: this args mustn't be used with args `distribution`? (maybe need a comment if it is the case)

2023-07-19 11:15 UTC, tdesveaux commented on nimp/base_commands/package.py
> +                        logging.warning("Encryption file not found, will use default encryption scheme")
I think we should warn if for_distribution is enabled but no encryption is provided.

Also, logging the encryption_file path here would be good for debug purposes since it's formatted and all.

2023-07-31 14:03 UTC, jasugun commented on nimp/base_commands/package.py
> +            #     package_command += [ '-NoCompile' ]
This was an error it should remain as it was before

2023-07-31 17:36 UTC, tdesveaux requested changes

2023-07-31 17:36 UTC, tdesveaux commented on nimp/base_commands/package.py
> +                if hasattr(env, 'xsx_encryption_file') and env.xsx_encryption_file is not None:
This could be simplified with `getattr(env, 'xsx_encryption_file') is not None:`

2023-07-31 17:36 UTC, tdesveaux commented on nimp/base_commands/package.py
> +                is_default_encryption_scheme = True
Won't this block be executed for other platform than XSX?
If so, these warnings might be a bit aggressive in these cases, so they should be only if the target platform is XSX

2023-09-04 13:43 UTC, jasugun commented
@tdesveaux All issues adressed thanks for the comments

2023-09-04 15:07 UTC, tdesveaux commented on nimp/base_commands/package.py
> +                is_default_encryption_scheme = True
I think this is still the case. The warning will be for all configurations not just XSX?

2023-09-04 15:51 UTC, jasugun commented on nimp/base_commands/package.py
> +                is_default_encryption_scheme = True
You're right :)

2023-09-04 16:14 UTC, tdesveaux approved these changes

2023-09-05 08:04 UTC, merged